Step3 완료했습니다.
code-squad/java-monster-race pull request #63
Opened 2020-02-07 12:53 UTC by ksundong

1. 처음 작성했을 때, 인터페이스 등 객체지향의 원리를 사용하라고 되어있었는데 제가 느끼기엔 객체지향이 필요한 부분인가? 라는 생각이 들었습니다.
   - 객체지향은 능력의 유무가 더 중요하다고 어제 수업을 들었는데, 여기에선 능력의 정도 차이만 있어서 적용하고 보니  불필요한 것 같아 규모가 더 커지면 적용을 고려해보려고 합니다.

2. Enum Class에 추상 메소드를 사용하는 방식도 고려해보고자 합니다. (Switch - Case 문을 줄일 방법)

2020-02-09 07:01 UTC, guswns1659 reviewed
코드 잘 봤습니다!!

2020-02-09 07:01 UTC, guswns1659 commented on src/main/java/dev/idion/Race.java
> +        Arrays.stream(monsters).forEach(monster -> attemptMoveMonster(random, monster));
코드 잘 봤습니다!! 
코드보고 저도 몇 군데 forEach로 변경하니 의미도 명확하고 간결해지네요!

2020-02-09 07:01 UTC, guswns1659 commented on src/main/java/dev/idion/Monster.java
> -        }
지우신 코드지만 switch문을 참고해서 짜보니 제 코드가 훨씬 간결해졌네요! 감사합니다!

2020-02-09 07:02 UTC, ksundong commented on src/main/java/dev/idion/Race.java
> +        Arrays.stream(monsters).forEach(monster -> attemptMoveMonster(random, monster));
아! 그 인텔리제이에서 for문 블럭하고 alt+enter하시면 람다식으로 변환해 줘요!
for loop 있을 때마다 한 번 해보고 좋은 쪽을 선택하는게 좋은거같아요!

2020-02-09 07:03 UTC, ksundong commented
> 코드 잘 봤습니다!!

@guswns1659 제 코드 읽으시다가 읽기 불편하시거나, 이렇게 바꿨으면 좋겠다는 제안도 언제든 환영입니다!

2020-02-09 07:37 UTC, guswns1659 commented on src/main/java/dev/idion/Race.java
> +        Arrays.stream(monsters).forEach(monster -> attemptMoveMonster(random, monster));
오.. 인텔리제이 진짜 똑똑이네용.. 감삼다 ㅎㅎ

2020-02-10 06:48 UTC, honux77 commented
@ksundong 이 PR 리뷰어님께 넘겨 볼게요. 저도 피드백을 함께 보고 싶어서요. 시간이 좀 걸릴 수 있으니 양해 부탁드려요.

2020-02-10 06:49 UTC, honux77 commented on src/main/java/dev/idion/Race.java
> +        Arrays.stream(monsters).forEach(monster -> attemptMoveMonster(random, monster));
긍정적인 피드백의 좋은 예 ㅎㅎ 좋네요.

2020-02-10 06:50 UTC, ksundong commented
> @ksundong 이 PR 리뷰어님께 넘겨 볼게요. 저도 피드백을 함께 보고 싶어서요. 시간이 좀 걸릴 수 있으니 양해 부탁드려요.

허어억...

2020-02-10 09:00 UTC, wheejuni requested changes
안녕하세요. 리뷰어 정휘준입니다. 
첫 리뷰를 받게되신 것을 환영합니다. ㅋㅋ

전반적으로 고생하고 학습하며 짠 코드라는 것이 느껴져 코드를 보는 내내 기분이 좋았습니다. 
다만 아래 사항을 좀 더 생각해 봅시다. 

1. `private` 메소드를 너무 남발하고 있지 않은지 되돌아봅시다. 
클래스에 수많은 `private` 메소드를 남발하는 것은 그 클래스가 해야할 기능 대부분이 **유닛 테스트되지 않아도 상관없다** 는 의미일 수 있습니다. 메소드 단위의 유닛 테스트가 어려워지는 것은 또한 리팩토링의 가능성을 극적으로 줄입니다.
공개된 메소드 간 중복 코드가 발생하여 private을 활용하는 것은 좋으나, 지나치게 남용하고 있진 않은지, 그리고 이 private method는 어떤 중복을 제거하고 있는지 고민하여 봅시다. 

2. 자바 유틸성 클래스들의 역할과 범위에 대해 정확히 학습한 후 사용합시다. 
특히 `SecureRandom` 과 `Random` 의 차이에 대해서는 한번 꼭 짚고 넘어가기 바랍니다. 

3. 클래스를 설계하고 클래스에 위임할 수 있는 기능을 발견하고자 노력하고, 발견했다면 과감히 클래스를 분리합시다.

아마 제가 자주 코드스쿼드에 갈 수 있을 것 같아요.
궁금한 사항은 DM을 줘도 좋고 여기에 댓글로 남겨도 좋습니다. 대면 요청(?) 하셔도 상관없습니다.

감사합니다!

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Game.java
> +        IntStream.range(0, monsters.length).forEach(this::makeMonster);
`stream API` 를 적극적으로 활용하려는 시도는 좋습니다.
그러나 굳이 이렇게 해야 할 이유는 없습니다. 

문맥상 의미를 보면 `monsters.length` 만큼 순회하며 몬스터를 준비하는 과정인데 명시적으로 for loop을 도는 것이 의미에도 더 맞다고 보여집니다.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
`NoSuchAlgorithmException` 은 `java.security` 패키지에서 암호화/복호화 관련 로직을 핸들할 때 던지려고 설계된 예외입니다. 
기존 예외를 재활용하려는 시도는 좋았습니다만 완전히 취지가 다른 예외 클래스를 재활용하는 것은 그리 좋아보이진 않습니다. 
`RuntimeException` 을 상속받는 새로운 예외 클래스를 설계해 보기 바랍니다.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Printer.java
> +    public void printWinnerMonster(Map<Integer, List<String>> rankMap, int winnerMoveCount) {
제가 이해하기로 `rankMap` 의 역할범위는 1. 몬스터가 움직인 횟수별로 2. 몬스터의 이름을 기록하는 것으로 생각됩니다. 
그렇다면 그 역할을 할  수 있는 새로운 클래스를 설계해봅시다. 
그리고 이 클래스에 지금 `buildWinner()` 가 수행하고 있는 역할을 위임해 봅시다.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Printer.java
> +        winnerBuilder.delete(winnerBuilder.lastIndexOf(","), winnerBuilder.length());
`String.join()` 을 사용하여 리팩토링하여 봅시다. 
이 곳에서도 `forEach` 의 사용이 불필요해보이지만 사용하고자 한다면 `Collectors.joining()` 을 사용해봅시다.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Game.java
> +
`monster.move()` 를 호출하기 위해 왜 이렇게 많은 메소드가 필요했나요?

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Monster.java
> +        moveCount += monsterType.moveMonster(SecureRandom.getInstanceStrong());
굳이 `NoSuchAlgorithmException` 을 사용한 이유가 여기에 있었네요. 
그런데 우리는 이번 애플리케이션에서 암호화 키나 토큰을 발행하는 것이 아닌, 괴물의 발걸음 수를 얻고자 난수를 활용했습니다.
그렇다면 `Random` 클래스의 메소드들도 충분합니다. 
`SecureRandom` 과 `Random` 의 차이점에 대해 학습하고 그 용도를 정확히 해 봅시다.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Monster.java
> +        return monsterDistanceBuilder.toString();
`StringJoiner` 에 대해 학습하고 활용해 봅시다.
https://java.ihoney.pe.kr/503

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/MonsterType.java
> +    };
`enum` 이름은 영어로 가급적 지어주세요.

2020-02-10 09:00 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Input.java
> +        }
굳이 `while` 문으로 감쌀 이유가 없어 보이는데요, 특별한 이유가 있었나요?

2020-02-10 09:21 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
앗 Step4를 진행하는 과정에서 안그래도 필요없는 것 같아서 지웠습니다.
Step3에도 변경해서 바꾸겠습니다.

2020-02-10 09:22 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
앗 4를 진행중이군요. 네 바꿔주세요. 바꾼 후 머지한 다음 4 브랜치에도 반영합시다.

2020-02-10 09:27 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
해당사항 변경하여 푸시하였습니다. 혹시 제가 Resolve conversation을 누르면 될까요?

2020-02-10 09:30 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Game.java
> +        IntStream.range(0, monsters.length).forEach(this::makeMonster);
해당 부분 for문으로 변경하는 중에 궁금한 점이 생겼습니다.
혹시 바로 monsters.length를 사용해서 조건을 지정해주는게 좋을까요?
아니면 monsters.length를 변수로 저장해서 지정해주는게 좋을까요?

2020-02-10 09:33 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Monster.java
> +        moveCount += monsterType.moveMonster(SecureRandom.getInstanceStrong());
네!! `SecureRandom` 과 `Random` 클래스의 차이점에 대해 학습하고, 정리해보겠습니다!

2020-02-10 09:34 UTC, wheejuni commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
그래도 좋고요, 아마 변경사항을 자동으로 감지해서 알아서 가려주지 않나요?

2020-02-10 09:35 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Movable.java
> +    void move() throws NoSuchAlgorithmException;
지금 푸시되어있는 상태인데 가려지지 않아서요! 그럼 가리겠습니다!

2020-02-10 09:39 UTC, honux77 commented
@wheejuni 수고하셨어요. 두 분다 고생하셨습니다.

2020-02-10 09:39 UTC, merged

2020-02-10 09:41 UTC, ksundong commented
@wheejuni 감사합니다!! 코멘트 받은 내용 고치겠습니다!

2020-02-10 10:30 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Game.java
> +        IntStream.range(0, monsters.length).forEach(this::makeMonster);
해당 부분 찾아보니 변수로 저장해주는 편이 좋을 것 같아 그렇게 수정하도록 하겠습니다!

2020-02-10 10:33 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/MonsterType.java
> +    };
앗, 입력 값을 바로 switch 문에 적용시키려고 했던건데, 수정해보겠습니다!

2020-02-10 10:38 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Input.java
> +        }
잘못된 값을 입력받으면 다시 입력받기 위해서 이렇게 작성했습니다!

2020-02-10 10:41 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Game.java
> +
SecureRandom 때문에 불필요한 로직이 추가된 것 같습니다.
개선해보겠습니다!

2020-02-10 10:44 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Game.java
> +
```java
private void startGame() {
    Arrays.stream(monsters).forEach(this::attemptMoveMonster);
}

private void attemptMoveMonster(Monster monster) {
    for (int i = 0; i < attemptCount; i++) {
        monster.move();
    }
}
```

이런 형태로 고쳤습니다!

2020-02-10 10:55 UTC, ksundong commented on src/main/java/dev/idion/monsterrace/Printer.java
> +    public void printWinnerMonster(Map<Integer, List<String>> rankMap, int winnerMoveCount) {
오... 이걸 Monster를 관리하는 Manager로 역할을 주려고했는데 이 자체만으로도 클래스가 될 수 있겠네요!
감사합니다!