Step3 구현 완료
code-squad/java-monster-race pull request #69
Opened 2020-02-09 18:36 UTC by blossun

코멘트 주신 내용으로 리팩토링 하였습니다.
1. 접근한정자 수정
2. input 메소드들의 코드 중복 제거
3. 사용자 입력 값 검증 추가
4. main()에서 순서대로 호출했던 프로그램의 흐름을 private인 play()에서 진행하도록 수정

**Step3 구현**
[설계도]
* Monster 를 추상클래스로 변경하여 Runner, Flight, Espurr 가 상속받는다.
* 몬스터는 MonsterType(Enum)에 존재하는 type이여야 생성 가능하다.
- setForwardCount메서드 오버라이딩 - 각 자식클래스는 타입별로 한번에 전진 가능한 칸 수를 셋팅한다.

<img width="1000" alt="스크린샷 2020-02-10 오전 3 34 57" src="https://user-images.githubusercontent.com/35985636/74107722-56c36b00-4bb6-11ea-8963-fddaf1bb4c8f.png">

##### Monster 클래스
* monsterType : Monster 클래스가 가질 수 있는 종류 
* minCriteria : 전진가능한 최소 랜던값 기준
* fowardCount : 한 번에 전진 가능한 칸 수
* forwardPosition : 전진 위치 상태
* setForwardCount() : (abstract) 각 몬스터마다 fowardCount를 설정해준다. (Espurr는 move()할때마다 바뀜)
* move() : fowardCount만큼 앞으로 전진
* isAboveMinCriteria() : 랜덤값이 minCriteria(전진가능한 최소 랜던값 기준)이상 인지 체크
* toString() : 자신의 정보를 문자열로 반환 
  * 형식 : **"이름(monsterName) [타입(monsterType)] :  전진위치(forwardPosition)"**
  * ex) `하니 [달리기] : ----`

##### MonsterType Enum
* Monster 클래스가 가질 수 있는 타입에 대한 Enum
  * monsterType : Monster 클래스가 가질 수 있는 종류 
  * minCriteria : 전진가능한 최소 랜던값 기준
* valueOfType() : 입력한 monsterType이 MonsterType의 type과 같으면 MonsterType을 넘겨주고, 없다면 에러를 던져줌

##### InputHandler 클래스
* inputMonsterInfo() : 경주할 몬스터 이름과 종류를 입력받는 기능 구현
  * 입력 문자열의 공백을 제거 후, (콤마)를 delimiter(구분자)로하여 문자열배열로 반환
  * 형식에 맞지 않을 시 에러처리

**MonsterRace 클래스**
* createMonster() : 몬스터 정보를 입력받아 해당하는 타입의 Monster 생성
  * 몬스터 정보를 잘못 입력 시 재입력 받도록 에러 처리
* printWinner() : 우승자 이름 출력
* pickWinner() : 우승자 선정

2020-02-11 00:05 UTC, wheejuni requested changes
안녕하세요~ 좋은 아침입니다. 
코드 작성하시느라 고생 많으셨구요, 아래 리뷰 코멘트를 참고해주세요. 

아차, 질문에 대한 답변도 간단히 드려봅니다. 
자세한 건 @honux77 님께 여쭤보세요 ㅋㅋㅋ

1. 질문하신 내용에 답이 있어요. 
`현재 제 프로그램은` 이라고 하셨는데, 현재 상황에서 뭔가 더 develop되거나 확장성을 가질 이유가 없다면 당연히 `protected`로 해도 되죠. 

solar님이 곧 현업 개발자로 회사에서 상용 코드를 작성하게 될 텐데, 그때는 작성하시는 코드가 같은 패키지에서만 사용되리라는 보장을 할 수 없게 됩니다. 다른 패키지는 물론이고....심지어 **다른 프로젝트나 다른 언어로도** 호출할 일이 생길지도 모릅니다. 

물론 그때 일은 그때 고민하구요, 단순히 지금 구현된 반면을 보면 `protected`를 선택해도 좋아요. 다만 모든 선택에는 근거를 먼저 생각합시다. 

근거를 생각할 시간이 없거나 귀찮다면(?) `public` 으로 가는 것이 오히려 안전합니다. 

2. 당연히 가져도 되죠. 
이때, 한걸음 더 들어가 봅시다. 단순히 생성자를 갖고 있는다(?) 고 접근하지 말고 `Monster 객체를 만드는 동작을 정의한다` 는 개념으로 인터페이스를 설계하고, 이를 구현하는 enum을 만들어 봅시다. 

무슨 말인지 이해되시나요?

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/InputHandler.java
> +            return inputMonsterInfo();
재귀호출을 시도했군요! 좋습니다. 다만 로직 상에서 재귀호출이 발생할 경우,

- base case를 확실히 하고,
- 어느 정도의 재귀 호출이 발생할 가능성이 있을지를 

미리 염두에 두고 설계하면 좋겠습니다.

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/Monster.java
> +
유닛 테스트를 작성할 때 `isAboveMinCriteria()` 에 대한 테스트는 어떻게 이뤄질 수 있을까요? 
테스트하기 조금 더 용이한 구조는 어떤 구조일지 다시 한 번 생각해 보세요. (코드를 수정하라는 의미는 아닙니다.)

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/Monster.java
> +        sb.append(monsterName).append(" [").append(monsterType.getMonsterTypeName()).append("] : ");
`StringJoiner` 사용해주세요.
https://java.ihoney.pe.kr/503

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +            switch (monsterType.getMonsterTypeName()) {
`MonsterType` 이 각각 하나의 값을 갖는 enum constant일 텐데 굳이 `.getMonsterTypeName()` 을 호출해 분기해야 할 이유가 있었나요?

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +            return createMonster();
재귀호출 다시 등장! 
앞서서 코멘트 드린 내용 확인하시고 재귀호출 코드를 작성할 땐 늘 유의하세요.

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +        Comparator<Monster> comparator = Comparator.comparing(Monster::getForwardPosition);
이렇게 `Comparator` 를 별도로 빼는 것도 좋지만, 
`Monster` 클래스가 정렬돼야 할 기준(오름차순/내림차순)이 하나인 것으로 보이므로(맞게 본 건가요?)
`Monster` 클래스가 `Comparable` 인터페이스를 구현하도록 설계해보세요. 

https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html 참고하시고 `compareTo(Object o)` 메소드를 알맞게 구현해 주세요.

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +        monsterStream.forEach(System.out::println);
`java.util.List` 안에 `forEach(Consumer c)` 메소드가 있어, 
굳이 스트림 객체를 생성할 이유가 없습니다. 

https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html#forEach-java.util.function.Consumer-

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +    private List<Monster> winners;
하나의 클래스를 담는 컬렉션 객체를 여러개 두고, 단순한 목적에 따라 구분해서 사용하고 있습니다. 
물론 변수명을 적절히 잘 지어주셔서 혼동의 여지는 적다고 보지만, 그렇게 객체지향적인(?) 구조는 아니라고 생각됩니다. 

이 인스턴스 변수를 참조하는 후속 로직들을 보면 `ranking.get(0)` 과 같은 구현을 하고 있습니다. 
`MonsterRanking` 과 같은 클래스가 존재하면서 그 객체에게 "1등이 누구냐?" 고 물어보는 구현을 가져가면 좋을 듯합니다.

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterRace.java
> +        winners = new ArrayList<>();
개인 취향이긴 한데 생성자 안에서 인스턴스 변수를 참조할 때는 명시적으로 `this` 를 선언해 줍시다. 
물론 `NoArgsConstructor` 라서 조금 애매하긴 합니다만....

2020-02-11 00:05 UTC, wheejuni commented on src/main/java/dev/solar/MonsterType.java
> +        return Arrays.stream(MonsterType.values())
`.values()` 를 응용한 구현 좋았습니다. 나이스

2020-02-11 02:04 UTC, blossun commented on src/main/java/dev/solar/InputHandler.java
> +            return inputMonsterInfo();
네 유의해서 사용하겠습니다. 🙂

2020-02-11 02:04 UTC, blossun commented on src/main/java/dev/solar/Monster.java
> +
고민해보겠습니다!

2020-02-11 02:36 UTC, honux77 commented on src/main/java/dev/solar/InputHandler.java
> +            return inputMonsterInfo();
다른 분들도 재귀를 많이 사용했는데 이 정도는 나쁘지 않네요. 브라이언 피드백이 딱 좋습니다.

2020-02-11 05:09 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +        monsterStream.forEach(System.out::println);
넵 수정하겠습니다!!

2020-02-11 05:09 UTC, blossun commented on src/main/java/dev/solar/Monster.java
> +        sb.append(monsterName).append(" [").append(monsterType.getMonsterTypeName()).append("] : ");
넵 수정했습니다!

2020-02-11 05:46 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +            switch (monsterType.getMonsterTypeName()) {
사용자 입력 문자를 비교한다고 착각하고 짠 것 같습니다. 😭수정했습니다!

2020-02-11 06:29 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +        winners = new ArrayList<>();
this 를 불필요하게 쓰는 건가 싶어서 삭제 했었는데 명시적으로 선언해주는게 좋은거군요!! 수정하겠습니다.

2020-02-11 08:02 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +            return createMonster();
네 알겠습니다!

2020-02-11 08:05 UTC, merged

2020-02-11 08:06 UTC, honux77 commented
아차 실수로 제가 머지해 버렸네요 ㅜㅜ.

2020-02-11 08:08 UTC, wheejuni commented
빨리 revert해주세요 ㅋㅋㅋ

2020년 2월 11일 (화) 17:06, Hoyoung Jung <notifications@github.com>님이 작성:

> 아차 실수로 제가 머지해 버렸네요 ㅜㅜ.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/code-squad/java-monster-race/pull/69?email_source=notifications&email_token=AF5ZL5BY4VR7DSEGXXJMWDLRCJL7TA5CNFSM4KSDPSD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELLQOEA#issuecomment-584517392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5ZL5GVGUCRI2F34RZEEDLRCJL7TANCNFSM4KSDPSDQ>
> .
>
-- 
Hwi Jun Jeong *정휘준*

Lv.1 Backend Developer @ NAVER Corp <http://www.navercorp.com>
Geek, Enthusiast.

For work-related purposes, please contact me at hwijun.jeong@navercorp.com
.
==================================
+82-10-2018-6050
facebook.com/wheejuni
github.com/wheejuni

2020-02-11 08:10 UTC, ksundong commented
@wheejuni 번호나오셨어요!

2020-02-11 08:12 UTC, wheejuni commented
@ksundong 수정했습니다. 이메일로 쉽게 댓글남길 방법을 시도해봤는데 서명때문에 안되겠네요.

2020-02-11 13:40 UTC, blossun commented
답변 감사합니다!! 정확히 궁금했던 점을 알게되었어요.  단순히 `생성자를 만든다`가 아닌  `Monster 객체를 만드는 동작을 정의한다` 는 개념으로 나아가는게 중요한 것 같네요. 

코멘트주신 사항 수정하였고, 다음 두개 사항에 대해서도 좀 더 공부한 뒤 리팩토링 하겠습니다. 
1.  Comparable 인터페이스를 구현하도록 리팩토링
2. 몬스터 랭킹 관련 코드를 객체 지향적으로 재설계

` isAboveMinCriteria() 에 대한 테스트`는 아직 잘 모르겠습니다 ㅠㅠ 4단계에서 테스트를 진행해보면서 고민해보겠습니다.

2020-02-12 01:27 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +        Comparator<Monster> comparator = Comparator.comparing(Monster::getForwardPosition);
네 정렬기준이 하나인데 이렇게도 할 수 있네요. 👍 좋은거 같아요!!! 수정했습니다

2020-02-12 05:11 UTC, blossun commented on src/main/java/dev/solar/MonsterRace.java
> +    private List<Monster> winners;
MonsterRace에서 게임결과와 관련된 코드를 따로 분리하여 RacingResult 클래스로 만들었습니다.  Monster가 Comparable를 구현하여 별도의 ranking 리스트는 불필요하게 되었고, RacingResult에서 우승자를 선정하고 게임결과와 우승자를 출력해주도록 하였습니다. 

사용자 입력부를 나눈 것처럼 게임결과를 처리하는 부분에서 출력부도 나누는 것이 좋을지 고민중입니다!