Step2
code-squad/java-monster-race pull request #76
Opened 2020-02-10 07:23 UTC by Hamill210

20/02/10 프로그램 구현

[기능 요구사항]
* 1단계와 같다.

[프로그래밍 요구사항]
* indent(인덴트, 들여쓰기) depth를 2단계에서 1단계로 줄여라.
* depth의 경우 if문을 사용하는 경우 1단계의 depth가 증가한다. if문 안에 while문을 사용한다면 depth가 2단계가 된다.
* else를 사용하지 마라.
* 메소드의 크기가 최대 10라인을 넘지 않도록 구현한다.
* 메소드가 한 가지 일만 하도록 최대한 작게 만들어라.
* stream은 가능하면 사용하지 않는다.
* 자바 코딩 컨벤션을 지키면서 프로그래밍한다.

[느낀점]
* Method를 최대한 작게 만들어서 기능을 줄이고 depth의 깊이를 줄일 수 있었습니다.
* 최대한 코딩 컨벤션을 지키면서 코드를 짰습니다.
* README 를 작성하면서 다시 한번 코드를 되돌아 볼 수 있었습니다.

2020-02-11 16:20 UTC, kyucumber requested changes
고생 많으셨습니다! 👍 

깔끔하게 작성 잘 해주셨네요.
몇가지 간단한 내용을 남겼습니다.

혹시 의문점이 있으시면 코멘트 남겨주세요!

2020-02-11 16:20 UTC, kyucumber commented on .idea/encodings.xml
> +</project>
과제의 내용과 별개이지만, 혹시나 도움이 될 수 있을 것 같아서 공유드립니다.

![image](https://user-images.githubusercontent.com/34656258/74032003-406eb100-49f6-11ea-875f-be6d0f72f939.png)

**newline을 붙여야 하는 이유 관련 문서**

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

> 인텔리제이에서 자동으로 저장 시 newline을 붙이도록 하는 설정

![image](https://user-images.githubusercontent.com/34656258/69198460-1be20600-0b78-11ea-83cd-c8fc5189c7ba.png)

2020-02-11 16:20 UTC, kyucumber commented on src/main/java/com/han95210/codesquad/monsterRace/step2/MonsterRace.java
> +        if (randomNum >= 4) {
이런 4 같은 값은 상수를 활용하시는게 어떨까요?

4라는 Integer 값을 봤을 때 이 값이 어떤 목적으로 정의되었는지 이해하기 힘들 수 있어요.

```java
private static final Integer FORWARD_NUMBER = 4;
```
```suggestion
if (randomNum >= FORWARD_NUMBER) {
```

2020-02-11 16:20 UTC, kyucumber commented on src/main/java/com/han95210/codesquad/monsterRace/step2/MonsterRace.java
> +        scanner = new Scanner(System.in);
아래와 같은 할당이 `getNumberOfMonster`, `getNumberAttempts` 두 군데서 실행되고 있네요

```java
new Scanner(System.in);
```

`new Scanner(System.in)`를 통해 Scanner 인스턴스가 두번 생성되어 질 것 같습니다.
성능상 사실 큰 영향은 없겠지만 변수로 가지고 있으니 생성자 등에서 한번만 호출되어질 수 있도록 변경하는건 어떨까요?

```java
public MonsterRace() {
    scanner = new Scanner(System.in);
}
```

그리고 모든 읽기 작업이 끝났을 때, `close()`를 하면 될것 같습니다.

2020-02-11 16:20 UTC, tramyu commented on src/main/java/com/han95210/codesquad/monsterRace/step2/MonsterRace.java
> +    }
코드 내에서 `(int) (Math.random() * 10);` 라는 코드가 두번 정도 호출되어지고 있네요.

이 부분은 private method로 추출해서 사용해도 될 것 같아요.

```java
public Integer getRandomNumber(int range) {
    return (int) (Math.random() * range);
}
```

```suggestion
    private String getRandomDash() {
        if (getRandomNum(10) >= 4) {
             return "-";
        }
        return "";
    }
```

2020-02-11 16:20 UTC, tramyu commented on src/main/java/com/han95210/codesquad/monsterRace/step2/MonsterRace.java
> +    private static String getRandomDash() {
제가 놓친 게 있을 수 있는데 이 부분은 `static`으로 정의되지 않아도 될 것 같아요!

2020-02-11 16:20 UTC, tramyu commented on src/main/java/com/han95210/codesquad/monsterRace/step2/MonsterRace.java
> +    private static String getDashStr(int numberAttempts) {
이 부분도 `static`으로 정의되지 않아도 되지 않을까요?

2020-02-11 16:20 UTC, tramyu commented on src/main/java/com/han95210/codesquad/monsterRace/step1/Step1.java
>      String getForwardCount(int numberAttempts) {
메소드의 이름만 봤을 땐 Count, 반환 값으로 숫자를 가질 것 같은데

실제로는 진행하는 횟수 만큼의 "-" 문자를 합쳐서 반환해주는 내용을 가지고 있어서 혼란을 줄 수 있을 것 같네요!

2020-02-12 06:13 UTC, merged

2020-02-12 08:45 UTC, Hamill210 commented
피드백 감사합니다!!