Step3 추가사항
code-squad/java-monster-race pull request #83
Opened 2020-02-11 13:35 UTC by beemiel

- 클래스 구조

![클래스 구조](https://i.imgur.com/kQt0kpL.png)

- 요구사항에 따른 추가 사항 및 변경 사항

1. 비행,달리기,에스퍼 세 타입의 클래스를 추가하고 기존의 Moster클래스를 추상클래스로 만들어서 상속받음. 
2. enum을 사용하여 입력받은 타입을 검사하고 타입에 맞는 객체를 생성해줌.
3. 모든 라운드가 종료된 후 최종 우승자를 계산한 후 출력

- 클래스 상세
  - Monster Class
    - String name - 몬스터의 이름
    - String type - 몬스터의 타입
    - int isRunNumber - 난수가 true인 조건
    - String totalMove - 총 걸음 수
    - Random random - random 재활용
    - StringBuffer stringBuffer - 문자열 추가
    - getName() - 몬스터의 이름 반환
    - setName(String name) - 몬스터의 이름 저장
    - isMove() -  isRunNumber 보다 크거나 같을 경우 true 반환
    - moveOrStop() - 추상메소드
    - run(int count) - 입력받은 카운트 수만큼 반복
    - toString() - 몬스터의 이름,타입,총 걸음 수 출력
  - Running Class
    - moveOrStop() - isMove()의 값이 true일 경우 1 추가
  - Flying Class
    - moveOrStop() - isMove()의 값이 true일 경우 3 추가
  - Psychic Class
    - moveByRandom() - 움직임 수를 난수로 생성 후 반환
    - moveOrStop() - isMove()의 값이 true일 경우 moveByRandom()만큼 추가
  - Message Class
    - 사용자에게 안내할 콘솔 출력문 모음
  - Race Class
    - int monster - 몬스터의 수
    - int count - 라운드 수
    - ArrayList<Monster> monsters - 입력받은 몬스터 리스트
    - ArrayList<Monster> winnerMonsters - 우승한 몬스터 리스트
    - Message message - 콘솔에 메세지 출력
    - Input input - 사용자로부터 입력을 받음
    - Output output - 사용자에게 경기 결과 출력
    - racing() - 순차적으로 경기 실행
    - setting() - 경기 시작 전 몬스터 수, 라운드 수, 몬스터 정보를 세팅
    - makeMonster() - 몬스터 객체를 얻어 몬스터 리스트에 추가
    - calculateResults() - 최종 결과 연산 calculateHighRecod() 와 addWinnerMonster()  호출
    - addWinnerMonster() - 최고점과 같으면 우승자 리스트에 추가
    - calculateHighRecod() - 최고 점수 계산
  - Input Class 
    - Scanner scanner - 사용자에게 입력을 받기 위한 스캐너
    - Message message - 콘솔에 안내 문구 출력
    - inputMonster() - 몬스터 수 입력
    - inputMonsterInfo() - 몬스터 정보 입력, 그 정보로 생성된 객체 반환
    - inputCount() - 라운드 수 입력
    - close() - scanner 닫음 
  - MonsterType enum
    - 세 가지 타입 정의
    - getMonster() - monster 반환
  - Output Class
    - Message message - 안내 문구 출력
    - contenOfGame() - 콘솔에 경기 내용 출력
    - resultOfGame() - 콘솔에 경기 결과 출력

2020-02-13 02:56 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Flying.java
> +        super(type,6);
6같은 매직 넘버는 코드 가독성을 떨어뜨립니다. 상수를 하나 만들어서 이용해 주세요.

2020-02-13 02:57 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Flying.java
> +            stringBuffer.append("▷▷▷");
ㅋㅋㅋㅋㅋㅋ 귀엽네요.

2020-02-13 03:01 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Input.java
> +            } catch (Exception e){
Exception 말고 구체적인 exception을 처리해 주는게 좋아요.

2020-02-13 03:42 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Input.java
> +    public int inputMonster() throws NumberFormatException{
이 메소드가 입력과 출력을 담당하고 있어서, 이름보다 많은 일을 하는 느낌이에요. 클래스도 마찬가지고
message가 있긴 하지만 InputView 의 역할을 하고 있네요.
메소드 안에서 message읨 메소드를 출력하는 것보다 상위 객체가 하는게 더 좋지 않을까 생각이 듭니다.

객체의 메소드는 한가지 일을 하도록 하는게 좋아요.

2020-02-13 04:20 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Input.java
> +                monsterType.getMonster().setName(name);
아직 monsterType을 보지 않았는데 이 부분도 해당 코드만으로는 조금 동작의 유추가 어렵네요. 가능하면 현재 코드만으로 이해가 되도록 짜면 좋을 것 같아요.

2020-02-13 04:20 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Message.java
> +
static 클래스에 static 메소드를 사용해도 좋을 것 같습니다. 상태가 없으니까요.

2020-02-13 04:21 UTC, honux77 commented on README.md
> +    - moveOrStop() - isMove()의 값이 true일 경우 1 추가
1과 3은 뭘까요?

2020-02-13 04:28 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/MonsterType.java
> +public enum MonsterType {
enum의 선언과 사용이 조금 이상한 듯해요. 다시 공부해 보고 수정하거나, 아예 enum을 빼 보세요.

2020-02-13 04:29 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Message.java
> +    final String MONSTER_INFO = "\n경주할 몬스터 이름과 종류를 입력하세요 (예> 크롱,FLY)";
사용자에게 FLY라고 입력을 시키는 건 너무 가혹한데요. 원래의 요구사항대로 비행으로 입력하도록 고치면 좋겠네요.

2020-02-13 04:35 UTC, honux77 commented on src/main/java/com/beemiel/monsterrace/Message.java
> +    final String MONSTER_INFO = "\n경주할 몬스터 이름과 종류를 입력하세요 (예> 크롱,FLY)";
그리고 현재 프로그램이  정상적으로 돌아가지 않아요 ㅜㅜ.

2020-02-13 04:36 UTC, honux77 requested changes
정상적으로 돌아가도록 고쳐 주세요. PR을 다시 보낼 필요는 없고, 이 브랜치에서 작업하고 push만 하면 됩니다.

2020-02-14 08:00 UTC, beemiel commented
@honux77 수정을 해보았습니다. enum 아직도 아닌가요? 빼는게 나을까요?

2020-02-15 13:27 UTC, honux77 approved these changes
좀 깔끔해졌네요. 타입 찾는 부분을 그렇게까지 해야 하나 싶긴 한데 그래도 괜찮아요 ㅎㅎ

2020-02-15 13:28 UTC, merged