Step3 구현
code-squad/java-monster-race pull request #84
Opened 2020-02-11 16:19 UTC by bohyeon-n

- 타입별로 몬스터 클래스를 구현함
- 몬스터 타입을 정의하기 위해 enum 클래스를 사용함 
- 게임 승자를 출력하는 기능을 추가함 
- 레이스 결과 형식을 '이름[타입] : 결과' 로 수정함
- 사용자에게 몬스터 이름과 타입을 받는 기능을 추가함 

step2 리뷰를 참고하여 수정하고 step3 요구사항을 추가하였습니다.
객체지향을 지향하고자 하였으나 객체지향이 뭔지 아직 잘 모르겠습니다...! !

2020-02-11 20:07 UTC, wheejuni requested changes
새벽 한시에 풀 리퀘스트를 여는 열정 좋습니다. 
코드 전반에서 아쉬웠던 점 아래와 같이 정리해 봅니다.

1. getter/setter 는 단순한 코딩 컨벤션을 넘어.... Java 언어가 갖고 있는 일종의 규약이기도 해요. 
https://imasoftwareengineer.tistory.com/101 참고하고 getter/setter 네이밍 규칙을 꼭 꼭 준수해 주세요. 
(아 참, 위 링크에서 `Serializable` 관련 내용은 굳이 안 참고하셔도 됩니다. 아직은...) 

2. 명사형 메소드 이름을 지양하시고, 메소드의 역할과 행위를 명확히 드러내는 이름을 생각해 주십시오. 

3. 접근 제어자를 (명확한 이유가 없다면) 빼먹지 맙시다.

늦은 밤까지 수고 많으셨어요. 조금만 다듬어 봅시다!

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/EsperMonster.java
> +        this.type = "초능력";
`this.type` 이라면 어차피 받을 수 있는 타입이 한정적이었을 텐데, enum을 쓰는 건 어땠을까요. 
그리고 그 enum을 super constructor에 같이 넘기고요.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/EsperMonster.java
> +    }
고민해볼 만한 포인트가 있네요. 
아마 `forwardNumber()` 를 오버라이드해야 할 이유가 있었다면, 몬스터에 타입별로 수행해야 할 이동거리 계산 로직이 달랐기 때문이겠죠.
그렇다면 해당 로직은 몬스터의 타입에 종속성이 걸리는 것으로 보이는데, 그렇다면 이 계산 로직은 몬스터의 type enum에 존재해도 되는 거였네요. 
방법은 여러가지이지만 저 같으면 그렇게 했을 것 같습니다. 
어쨌든 지금은 외부에서 호출되지 않을 메소드를 `public` 으로 선언하고 상속받으며 오버라이드하게 설계한 것이 그리 깔끔해 보이진 않습니다.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterFactory.java
> +    public Monster createMonster(String name, MonsterType type) {
`MonsterType` 을  좀 더 활용해봅시다! 제 생각엔.....

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterGame.java
> +    public List<Monster> winner() {
불분명한 메소드 이름이고, 명사형 메소드 이름은 좋아보이지 않네요.
좀 더 직관적이고 메소드의 행위를 정의할 이름을 생각해주세요.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterGame.java
> +            break;
1등이 여러명일 수 있다는게 의외로 까다로운 요구조건이네요.
구현하신 접근도 나쁘진 않지만, 아래 링크도 한 번 참고해 주세요.
https://stackoverflow.com/questions/36428439/how-do-i-collect-multiple-maximum-values-from-a-list

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterGame.java
> +    public List<Monster> monsters() {
getter라면 `get` 접두사를 붙여줍니다.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterGame.java
> +        return String.valueOf(character).repeat(times);
다음 프로젝트부터 Java 8로 고정이 되는데 이 메소드는 쓸 수 없겠네요.
이처럼 새로운 피쳐를 사용할 때는 
- 꼭 Javadoc을 확인하고 
- **since** 항목을 더블 체크 합니다. 

이 코드의 경우 JDK 8이 인스톨되어 있는 사람은 아예 컴파일 에러가 날 겁니다. 
혼자 하는 프로젝트여서 상관이 없었지만, 앞으로 늘 유념해주세요.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterMain.java
> +        MonsterFactory monsterFactory = new MonsterFactory();
팩토리는 시즈탱크, 벌쳐, 골리앗 등을 뽑는 시설이기때문에 대부분의 경우 짓는데 비용이 많이 듭니다. 
미네랄 200원 가스 50원이었나...

하여 대부분의 경우 Java 코드에서는 팩토리를 **정적으로 선언** 하거나 **싱글톤 객체** 로 설계해 사용합니다.
팩토리 클래스를 설계한 것은, 팩토리에서 쏟아져나올 객체 물량 러시를 가기 위함이지 공장 자체를 많이 만들기 위한 건 아니기 때문입니다. 

팩토리 클래스의 생성자를 호출해 로직이 돌 때마다 새 공장을 만들어내는 것은 좋아보이지 않습니다.
`new MonsterFactory()` 하지 않고도 객체를 만들 수 있는 방법을 고민해 주세요.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterMain.java
> +            }
`MonsterType.getByKey()` 를 재설계하여 `java.util.Optional` 을 활용할 수 있는 방안을 고민해 주세요.

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterMain.java
> +    InputView inputView;
접근제어자를 붙입시다! 접근제어자는 나의 친구

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/MonsterFactory.java
> +        return null;
`null` 을 받는 쪽에서 받을 준비가 되어있나요?

2020-02-11 20:07 UTC, wheejuni commented on src/main/java/Monster.java
> +    String type;
굳이 `package-private` 할 필드가 아닌 것 같은데 `protected` 를 붙여주세요.

2020-02-12 06:23 UTC, honux77 commented
수고 많으셨어요. @bohyeon-n 리뷰 꼼꼼히 읽고 다음 단계에 반영할 수 있는 것들 반영해 보세요.

2020-02-12 06:23 UTC, merged