Mosnter Race Step3
code-squad/java-monster-race pull request #88
Opened 2020-02-12 08:55 UTC by hsik0225

### UML

---

![Step3 UML](https://user-images.githubusercontent.com/56301069/74316201-f7f62100-4d70-11ea-860b-817184f2b763.png)

### 구현 내용

---

- Input 받는 값들이 제대로 들어왔는지 확인하기 위해 정규표현식을 사용하였다.
- Monster의 타입별로 Enum을 만들어 타입에 따른 몬스터 객체를 생성하였다.
- Runner, Fly, Esper 클래스를 따로 생성하지 않았다.

타입 별로 다른 건 움직일 수 있는 조건(Runner=4, Fly=6, Epser=9)과 움직이는 거리(Runner=1, Fly=3, Epser=(int)(Math.random()*100)+1)이다.

- Output하기위한 문자열들을 Enum클래스에 열거하였다.

2020-02-12 10:41 UTC, hwijun-jeong commented on src/com/hsik0225/Input.java
> +    private static final Pattern MONSTER_INFO_PATTERN = Pattern.compile(".*([,])\\s*(비행|에스퍼|달리기)\\s*");
우와 멋집니다. 굳굳!

2020-02-12 21:42 UTC, wheejuni requested changes
고생 많으셨어요. 코드가 점점 좋아지는 느낌이네요. 
한 걸음 더 나아가기 위해 **패키지 구조 설계**에 대해서 고민해보는 것도 권합니다.

간단하게 참고할 만한 글 링크 얹어봅니다. http://tutorials.jenkov.com/java/packages.html

아래 코멘트 드린 사항 한번 읽어보시고 궁금하신 점은 언제든지 추가 질문 해주세요. 감사합니다!

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/Input.java
> +    private static final Pattern MONSTER_INFO_PATTERN = Pattern.compile(".*([,])\\s*(비행|에스퍼|달리기)\\s*");
우와 멋집니다. 굳굳!

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/Input.java
>          }
사용자가 의도한 인풋을 줄 때까지 반복한다는 로직은 잘 설계하셨지만,
`while`문의 조건 변수가 조금 한번에 읽히지 않는 것 같습니다. 
`boolean isCorrectInput` 과 같은 지역 변수를 따로 뺀 다음 그 변수를 while문의 조건에 넣도록 수정하는 건 어떨까요.

반복문, 조건문 등의 조건은 누가 읽어도 한번에 눈에 들어올 수 있도록 설계하는 것이 시간낭비를 막습니다.

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/Monster.java
> +        if(randomValue>=conditionalValue){
조건문의 소괄호와 중괄호 앞뒤로 한 칸씩의 공백을 둡니다.
https://naver.github.io/hackday-conventions-java/#space-between-keyword-parentheses

연산자 앞뒤로 한 칸씩 띄워줍니다. 
https://naver.github.io/hackday-conventions-java/#space-around-binary-ternary-operator

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterFactory.java
> +public enum MonsterFactory {
enum의 이름으로 `Factory` suffix는 어색합니다. 다른 이름을 고민해봅시다.

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterRace.java
> +import static com.hsik0225.OutputStrings.WINNER;
`import static com.hsik0225.OutputString` 정도로 한 뒤에....
`OutputStrings.WINNER` 와 같이 호출하는 게 더 직관적일 것 같습니다만 각자의 취향에 관한 문제라 선택에 맡겨둘게요.

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterRace.java
> +        for (int index = 0; index < monsterCount; index++) {
`index` 라고 하지 않고 `i` 라고 해도 됩니다.

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterRace.java
> +        int bound = 10;
설정값과 같이 사용되는 이런 변수는 클래스 상단에 `static final` 변수로 빼주는 것도 좋습니다.

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterRace.java
> +            }
두 조건문은 하나로 합칠 수도 있을듯? 싶네요??

2020-02-12 21:42 UTC, wheejuni commented on src/com/hsik0225/MonsterRace.java
> +            System.out.printf(MONSTER_INFO_AND_DISTANCE.toString(), monster.getName()
`MONSTER_INFO_AND_DISTANCE`가 이미 `String`인데 왜 또 `.toString()` 을 호출했나요?

2020-02-13 14:36 UTC, ksundong commented on src/com/hsik0225/MonsterRace.java
> +            System.out.printf(MONSTER_INFO_AND_DISTANCE.toString(), monster.getName()
printf는 toString이 안먹지 않나요?

2020-02-13 14:45 UTC, honux77 commented on src/com/hsik0225/MonsterRace.java
> +        for (int index = 0; index < monsterCount; index++) {
저도 i 추천

2020-02-13 14:47 UTC, merged

2020-02-14 04:57 UTC, hsik0225 commented on src/com/hsik0225/MonsterRace.java
> +        int bound = 10;
static final에 대해서 전혀 모르고 있었네요.
static final을 공부해볼 수 있는 좋은 기회가 되었습니다.