Step 3
code-squad/java-monster-race pull request #89
Opened 2020-02-13 02:19 UTC by MuseopKim

Step-2의 코드 리뷰를 반영하여 Step-3의 코드를 작성 하였습니다.

### 피드백 내용
- 메서드 오버라이딩시에 어노테이션 추가하기
- 불필요한 기본 생성자 삭제하기

### 구현 내용
![monster-race](https://user-images.githubusercontent.com/49878687/74395365-81c9eb00-4e52-11ea-8c9c-8cace05fb262.png)

- Monster 클래스를 추상 클래스로 선언 하고 추상 메서드를 정의 하였습니다. 달리기, 비행, 에스퍼 각 타입의 클래스로 각 추상 메서드를 구현 하였습니다. 몬스터의 타입에 따라 move의 판정기준과 이동거리가 다르므로 isMove()와 move()를 각자 다르게 구현 하도록 하였습니다.
- 각 몬스터 타입의 자료형을 열거형으로 선언 하였습니다.
- RacingGame 클래스에 하나의 기능으로 있던 입출력 부분을 InputHandler라는 별도의 클래스로 분리하였습니다.

### 해결해야 할 사항

- 몬스터의 이름과 타입을 입력 받고 저장하는 과정에서 하드코딩 한 것을 정돈된 코드로 바꾸고 싶습니다. 방법이 떠오르지 않아 더 많은 고민이 필요 할거 같습니다.
```java
    String[] properties = splitProperties();

    inputNameOfMonster = properties[0];
    String typeNameOfMonster = properties[1];
```

- 예외처리가 매우 미흡합니다. 이 부분에 대해서는 따로 공부를 많이 해야 할거 같습니다.

- 우승자를 선정하는 코드에서 depth가 2로 늘어났는데, 모든 depth를 1로 줄이고 싶습니다.
```java
    private void determineWinners(int maxValue) {
        for (Monster monster : monsters) {
            if (monster.moveCount == maxValue) {
                winners.add(monster);
            }
        }
    }
```

- 우승자를 출력하는 과정에서의 하드코딩을 정돈된 코드로 수정하고 싶습니다.
```java
        StringBuilder stringBuilder = new StringBuilder("우승자는 ");
        for (Monster monster : winners) {
            stringBuilder.append(monster.getName()).append(" ");
        }

        String printWinners = stringBuilder.append("입니다. 축하 합니다!").toString();
        System.out.println(printWinners);
```

### 질문 드리고 싶은 내용
Monster 클래스를 추상 클래스로 정의 하였습니다. 그런데 Monster 클래스를 추상 클래스를 정의하지 않고 isMove()와 move() 메서드를 각 몬스터 타입의 클래스에서 오버라이딩 해도 구현이 가능할거 같은데요. 굳이 추상 클래스를 선언하지 않아도 같은 기능을 구현할 수 있는 구조라면 사용하지 않는게 더 좋을까요? 조언을 부탁 드립니다.

2020-02-14 16:16 UTC, wheejuni requested changes
수고 많으셨습니다. 

해결해야 할 사항에 대한 힌트를 좀 드리자면 **클래스를 새로 만드는 것에 대해 두려움을 가지지 마세요.**
그리고 객체가 일하게 합시다. 객체에게 질문하고 객체가 답을 주게 설계해 보세요.
그러면 의외로 쉽게 해결될 겁니다.

수고 많으셨고요, 코멘트 참고하셔서 조금씩 수정해나가시면 좋겠습니다.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +    int setNumOfMonsters() {
`package-private` 을 고려하고 접근 제어자를 생략한 것으로 보이지만,
현재 패키지 구조가 직관적이지 않고, 추후 개선될 여지가 보이므로 일단은 `public` 을 붙여 주세요.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +            }
(그냥 생각해봅시다.)
만약 `Integer.parseInt()` 의 결과가 `int` 자료형 범위를 넘어가면 어떻게 될까요?

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +        } catch (IOException | NumberFormatException e) {
multi-catch 좋았습니다. 그런데 설계 측면에서....
`IOException` 과 `NumberFormatException` 두 예외 공히 자연수가 입력되지 않았을때 나오는 예외 맞죠?

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +    void setMonsterProperties() {
여기도 `public` 제어자 붙여 줍니다.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +            final String RUNNER = "달리기", FLYING = "비행", ESPER = "에스퍼";
상수 성격을 띄는 변수를 스코프 안에 선언하지 않습니다.
클래스 상단부로 올려서 어떤 메소드에서든지 참조할 수 있도록 합니다. 

아울러 `static` 아닌 변수에 upper case 사용하지 않습니다.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +            }
이런 목적으로 위에 상수를 선언했군요, 그렇다면, `Types` 의 각 타입이 문자열 형태로 입력값을 들고 있는게 좋지 않았을까요. 

그렇다면 이 스위치 문 자체를 날려버릴 수도 있습니다. 아래 `Types` 변경사항 코멘트로 이어갈게요.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/InputHandler.java
> +    }
`getter` 규약을 정확히 지키지 않았군요.
그렇다면 `get` prefix를 사용하는 것은 다시 생각해보기 바랍니다.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/Monster.java
> +    }
앞선 리뷰사항에서 `switch` 문을 개선하는데 활용해보면 좋겠네요.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/Monster.java
> +}
```Types.values()``` 를 활용해 각 값을 순회하면서, 
입력값에 맞는 값을 리턴해주는 static 메소드를 여기에 구현해보면 어떨까요?

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/Monster.java
> +enum Types {
별도의 파일로 분리해 주세요.

2020-02-14 16:16 UTC, wheejuni commented on src/race/monster/ragdoll/RacingGame.java
> +                maxValue = monster.moveCount;
이래서 접근 제어자가 필요한 걸지도 모르겠습니다. 
`getter` 나 `setter` 를 통해 접근하고 이렇게 필드에 직접 접근해서 값을 새로 쓰지 않는 방향으로 **반드시** 수정해 주세요.

2020-02-14 17:45 UTC, MuseopKim commented
@wheejuni 안녕하세요! 자세한 리뷰와 조언 남겨 주셔서 정말 감사합니다.
접근 제어자를 원리나 원칙 없이 사용한다는 느낌이 강하게 들었는데 코멘트 남겨주신 내용을 보면서 그 중요성에 대해 다시 한번 자각하게 되었습니다.
제시 해주신 몇 가지 키워드들에 대해서 공부를 하고, 구조와 설계에 대해서도 다시 고민을 해보겠습니다.
감사합니다.

2020-02-15 13:29 UTC, honux77 commented on src/race/monster/ragdoll/RacingGame.java
> +                maxValue = monster.moveCount;
반드시

2020-02-15 13:29 UTC, merged