Step1 구현
code-squad/java-monster-race pull request #9
Opened 2020-02-03 12:11 UTC by blossun

설계도 입니다.
MonsterRace 클래스
* monsterCnt : 경주할 몬스터 마릿수
* attemptCnt : 시도 횟수

Monster 클래스
몬스터 객체는 각자 구분가능한 id 값과 해당 회차에 앞으로 전진할 이동 횟수 값을 가진다.
* id - 몬스터 구분
* forwardCount - 전진 횟수 : random값 4이상으로
* toString() : overriding 전진 상태를 String으로 return
* setRandomCount() : 전진 횟수를 random으로 뽑아서 forwardCount에 합산

2020-02-04 00:20 UTC, honux77 commented
브랜치 이름은 그냥 step1로 해주세요. 제가 스크립팅해서 확인하는데 이름이 다르면 어렵습니다.

2020-02-04 00:23 UTC, honux77 requested changes
빌드가 안 됩니다. 확인하고 수정해 주세요.

2020-02-04 00:27 UTC, honux77 commented
엇 약간 수정하니 빌드 되네요. 죄송 ㅋ

2020-02-04 00:29 UTC, honux77 commented on src/main/java/dev/solar/Monster.java
> +    public void setRandomCount() {
메소드 이름은 세터보다 명확한 동작, 그리고 동사형이 더 좋습니다. run() 만으로 충분할 것 같네요.

2020-02-04 00:30 UTC, honux77 commented on src/main/java/dev/solar/Monster.java
> +    public String toString() {
ㅎㅎㅎ 이거 좋네요

2020-02-04 00:30 UTC, honux77 approved these changes
잘 구현하셨어요! 👍

2020-02-04 00:31 UTC, merged

2020-02-04 00:32 UTC, honux77 commented
참 커밋을 좀 더 잘게 나눠 보세요!

2020-02-06 12:32 UTC, blossun commented on src/main/java/dev/solar/Monster.java
> +    public void setRandomCount() {
넵 수정했습니다!