뽑기 프로그램 구현
code-squad/java-monster-race pull request #93
Opened 2020-02-14 07:57 UTC by honux77

요구사항과 관계없이 뽑기 프로그램을 구현했습니다. 아무나 리뷰해 주세요 ㅋㅋ.
(TO: 리뷰어 - 요건 리뷰어 업무에 포함시키면 안 됩니다.)

2020-02-14 08:57 UTC, ksundong commented
커밋이 너무 간략합니다. 원자적으로 커밋해주세요.
😆

2020-02-14 09:23 UTC, ksundong requested changes
파일 테스트하는 것에 대해서 좀 더 알게된 것 같습니다.
IntelliJ에 Save Actions라는 플러그인이 있는데 저장시 자동으로 할 행동을 지정해줄 수 있습니다.
😄

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/resources/logo.txt
> +
👍

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/build/reports/tests/test/classes/DataRepositoryTest.html
> +<!DOCTYPE html>
테스트 결과 파일도 커밋대상인가요??

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/build/resources/main/logo.txt
> +
👍

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/DataRepository.java
> +
🤔

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/DataRepository.java
> +        s.close();
변수명은 의미 있는 이름으로 지어주세요.

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/DataRepository.java
> +        Collections.shuffle(members);
오 이런것도 있군요!

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/MainApplication.java
> +        m.display();
😅

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/DataRepository.java
> +            logo += l + "\n";
😱

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/MainFrame.java
> +    }
이렇게 WindowListner는 사용하지 않아도 다 Override 해줘야하나요?
😨

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/main/java/Table.java
> +    private String position;
의미가 명확해서 좋네요!

2020-02-14 09:23 UTC, ksundong commented on code-squad-java-app/src/test/java/DataRepositoryTest.java
> +        assertThat(f.exists()).isTrue();
File은 존재하는지도 테스트 해야되는군요!

2020-02-15 13:41 UTC, honux77 commented on code-squad-java-app/build/reports/tests/test/classes/DataRepositoryTest.html
> +<!DOCTYPE html>
아뇨 ㅋㅋ 당연히 아니죠. 지적 감사합니다. git add --all로 커밋했어요. <-- 반면교사

2020-02-15 13:41 UTC, honux77 commented on code-squad-java-app/src/main/java/DataRepository.java
> +
ㅋㅋㅋㅋㅋㅋㅋ 꼼꼼해

2020-02-15 13:41 UTC, honux77 commented on code-squad-java-app/src/main/java/DataRepository.java
> +        s.close();
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 지적 감사합니다.

2020-02-15 13:41 UTC, honux77 commented on code-squad-java-app/src/main/java/MainApplication.java
> +        m.display();
ㅎㅎㅎㅎㅎㅎ

2020-02-15 13:42 UTC, honux77 commented on code-squad-java-app/src/main/java/DataRepository.java
> +            logo += l + "\n";
ㅋㅋㅋㅋㅋㅋㅋㅋ 정말 죄송합니다.

2020-02-15 13:42 UTC, honux77 commented on code-squad-java-app/src/main/java/MainFrame.java
> +    }
네 이건 어쩔수가 없어요 ㅜㅜ

2020-02-15 13:42 UTC, honux77 commented on code-squad-java-app/src/main/java/Table.java
> +    private String position;
이야 칭찬받으니 의외로 기분이 좋네요!

2020-02-15 13:43 UTC, honux77 commented on code-squad-java-app/src/test/java/DataRepositoryTest.java
> +        assertThat(f.exists()).isTrue();
아 보통 모바일이나 앱 프로젝트하면 시작파일 위치 같은 거 잘 못 잡거든요. 
그래서 예전에는 하드 코딩했는데 테스트를 활용하면 좋을 것 같아서 했어요.

2020-02-15 13:43 UTC, merged

2020-02-15 13:50 UTC, ksundong commented on code-squad-java-app/src/test/java/DataRepositoryTest.java
> +        assertThat(f.exists()).isTrue();
오 하나 배웠습니다! 감사해요 honux!!